---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 24.10.2022 16:45
---

---@type ability_dbEntry
local entry

---------------------------------------

entry = database.abilities.GetTemplate()
entry.id = constants.abilities.stalker.q
entry.events.onAdd = function(caster, abilityid)
  messages.p("ability added: %s", abilityid)
end

entry.events.onCast = function(caster, target)
  messages.p("ability casted: %s", target)
end

database.abilities.Write(entry)

---------------------------------------



---------------------------------------