---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 24.10.2022 16:45
---

---@type item_dbEntry
local entry

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.orb_of_darkness
entry.name = "Тйомная Сфера"
entry.sign = "Она настолько тйомная что в дефолтном шрифте нет буквы йо"
entry.icon = "ReplaceableTextures\\CommandButtons\\BTNOrbOfDarkness.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.weapon
entry.hero_class = constants.hero_class.none
entry.is_single = true
entry.stats.dps = 10
entry.stats.armour = 5
entry.stats.max_life = 10
entry.events.onEquip = function(caster, item)
  messages.p("item was equipped: %s", item)
  TimerStart(CreateTimer(), 5, false, function()
    gitem.Delete(item)
    DestroyTimer(GetExpiredTimer())
  end)
end
entry.events.onDrop = function(caster, item)
  messages.p("item was dropped: %s", item)
end
entry.events.onDeath = function(item)
  messages.p("item was DESTROYED: %s", item)
end
database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.handmade_weapon_stalker
entry.name = "Кустарное ружьё"
entry.sign = "Продавец заверил, что 8 из 10 покупателей не приходят снова"
entry.icon = "Icons\\Items\\HandmadeWeaponStalker.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.weapon
entry.hero_class = constants.hero_class.stalker
entry.stats.dps = 10

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.handmade_weapon_medic
entry.name = "Кустарная мед станция"
entry.sign = "Продавец заверил, что 8 из 10 покупателей не приходят снова"
entry.icon = "Icons\\Items\\HandmadeWeaponMedic.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.weapon
entry.hero_class = constants.hero_class.medic
entry.stats.dps = 10

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.handmade_weapon_engineer
entry.name = "Кустарный тех-протез"
entry.sign = "Продавец заверил, что 8 из 10 покупателей не приходят снова"
entry.icon = "Icons\\Items\\HandmadeWeaponEngineer.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.weapon
entry.hero_class = constants.hero_class.engineer
entry.stats.dps = 10

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.handmade_weapon_sniper
entry.name = "Кустарная снайперка"
entry.sign = "Продавец заверил, что 8 из 10 покупателей не приходят снова"
entry.icon = "Icons\\Items\\HandmadeWeaponSniper.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.weapon
entry.hero_class = constants.hero_class.sniper
entry.stats.dps = 10

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.handmade_weapon_gunner
entry.name = "Кустарный пулемёт"
entry.sign = "Продавец заверил, что 8 из 10 покупателей не приходят снова"
entry.icon = "Icons\\Items\\HandmadeWeaponGunner.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.weapon
entry.hero_class = constants.hero_class.gunner
entry.stats.dps = 10

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.handmade_weapon_racketeer
entry.name = "Кустарная базука"
entry.sign = "Продавец заверил, что 8 из 10 покупателей не приходят снова"
entry.icon = "Icons\\Items\\HandmadeWeaponRacketeer.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.weapon
entry.hero_class = constants.hero_class.racketeer
entry.stats.dps = 10

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.handmade_weapon_pyromaniac
entry.name = "Кустарный огнемёт"
entry.sign = "Продавец заверил, что 8 из 10 покупателей не приходят снова"
entry.icon = "Icons\\Items\\HandmadeWeaponPyromaniac.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.weapon
entry.hero_class = constants.hero_class.pyromaniac
entry.stats.dps = 10

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.handmade_weapon_demolitionist
entry.name = "Кустарные гранаты"
entry.sign = "Продавец заверил, что 8 из 10 покупателей не приходят снова"
entry.icon = "Icons\\Items\\HandmadeWeaponDemolitionist.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.weapon
entry.hero_class = constants.hero_class.demolitionist
entry.stats.dps = 10

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.goblin_helmet
entry.name = "Гоблинский Шлем"
entry.sign = "Защитит любую гоблинскую голову, несмотря на свою схожесть с кастрюлей"
entry.icon = "Icons\\Items\\GoblinHelmet.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.accessory
entry.hero_class = constants.hero_class.none
entry.stats.max_life = 20

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.goblin_armour
entry.name = "Гоблинский Бронежилет"
entry.sign = "Внешне похож на куртку, но очень прочную"
entry.icon = "Icons\\Items\\GoblinArmour.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.armour
entry.hero_class = constants.hero_class.none
entry.stats.armour = 3

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.goblin_boots
entry.name = "Гоблинский Ботинок"
entry.sign = "Выглядит полезным, даже несмотря на то, что всего один"
entry.icon = "Icons\\Items\\GoblinBoots.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.accessory
entry.hero_class = constants.hero_class.none
entry.stats.max_life = 15

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.goblin_gloves
entry.name = "Гоблинские Перчатки"
entry.sign = "Специальные удобные перчатки для любой работы"
entry.icon = "Icons\\Items\\GoblinGloves.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.accessory
entry.hero_class = constants.hero_class.none
entry.stats.max_life = 10
entry.stats.attackspeed = 25

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.goblin_cape
entry.name = "Гоблинский плащ"
entry.sign = "Позволяет выглядеть словно тот самый легендарный гоб!"
entry.icon = "Icons\\Items\\GoblinCape.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.accessory
entry.hero_class = constants.hero_class.none
entry.stats.str = 3
entry.stats.agi = 3
entry.stats.int = 3

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.beauty_pendant
entry.name = "Красивая подвеска"
entry.sign = "Она слишком прекрасна чтобы её проигнорировать"
entry.icon = "Icons\\Items\\BeautyPendant.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.accessory
entry.hero_class = constants.hero_class.none
entry.stats.hp_regen = 1
entry.stats.mp_regen = 1
entry.stats.max_life = 10
entry.stats.max_mana = 5

database.items.Write(entry)

---------------------------------------

entry = database.items.GetTemplate()

entry.id = constants.items.goblin_armoured_suit
entry.name = "Гоблинский Броне-Скафандр"
entry.sign = "Одно из лучших изобретений гоблинов"
entry.icon = "Icons\\Items\\GoblinArmouredSuit.blp"
entry.type = constants.item_types.permanent
entry.slot = constants.item_slots.armour
entry.hero_class = constants.hero_class.none
entry.stats.max_life = 50
entry.stats.armour = 12
entry.stats.str = 5
entry.stats.agi = 5
entry.stats.int = 5
entry.stats.attackspeed = 40
entry.stats.hp_regen = 2

database.items.Write(entry)

---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------



---------------------------------------