---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 24.10.2022 12:16
---

local entry
--------------------------------------------------------------------
-- heroes
--------------------------------------------------------------------

entry = database.units.GetTemplate()
entry.id = constants.heroes.stalker
entry.hero_class = constants.hero_class.stalker
entry.base_as_cd = 1.2
entry.base_ms = 330
entry.abil_list = constants.abilities.stalker
entry.stats.str = 10
entry.stats.agi = 10
entry.stats.int = 10
entry.stats.max_life = 100
entry.stats.max_mana = 100
entry.stats.armour = 2
entry.stats.dps = 15
entry.stats.hp_regen = 1
entry.stats.mp_regen = 5
database.units.Write(entry)

--------------------------------------------------------------------

entry = database.units.GetTemplate()
entry.id = constants.heroes.medic
entry.hero_class = constants.hero_class.medic
entry.base_as_cd = 1.5
entry.base_ms = 330
entry.abil_list = {}
entry.stats.str = 10
entry.stats.agi = 10
entry.stats.int = 10
entry.stats.max_life = 100
entry.stats.max_mana = 100
entry.stats.armour = 2
entry.stats.dps = 15
entry.stats.hp_regen = 1
entry.stats.mp_regen = 5
database.units.Write(entry)

--------------------------------------------------------------------

entry = database.units.GetTemplate()
entry.id = constants.heroes.engineer
entry.hero_class = constants.hero_class.engineer
entry.base_as_cd = 1.0
entry.base_ms = 330
entry.abil_list = {}
entry.stats.str = 10
entry.stats.agi = 10
entry.stats.int = 10
entry.stats.max_life = 100
entry.stats.max_mana = 100
entry.stats.armour = 2
entry.stats.dps = 15
entry.stats.hp_regen = 1
entry.stats.mp_regen = 5
database.units.Write(entry)

--------------------------------------------------------------------

entry = database.units.GetTemplate()
entry.id = constants.heroes.sniper
entry.hero_class = constants.hero_class.sniper
entry.base_as_cd = 1.6
entry.base_ms = 330
entry.abil_list = {}
entry.stats.str = 10
entry.stats.agi = 10
entry.stats.int = 10
entry.stats.max_life = 100
entry.stats.max_mana = 100
entry.stats.armour = 2
entry.stats.dps = 15
entry.stats.hp_regen = 1
entry.stats.mp_regen = 5
database.units.Write(entry)

--------------------------------------------------------------------

entry = database.units.GetTemplate()
entry.id = constants.heroes.gunner
entry.hero_class = constants.hero_class.gunner
entry.base_as_cd = 0.8
entry.base_ms = 330
entry.abil_list = {}
entry.stats.str = 10
entry.stats.agi = 10
entry.stats.int = 10
entry.stats.max_life = 100
entry.stats.max_mana = 100
entry.stats.armour = 2
entry.stats.dps = 15
entry.stats.hp_regen = 1
entry.stats.mp_regen = 5
database.units.Write(entry)

--------------------------------------------------------------------

entry = database.units.GetTemplate()
entry.id = constants.heroes.racketeer
entry.hero_class = constants.hero_class.racketeer
entry.base_as_cd = 1.3
entry.base_ms = 330
entry.abil_list = {}
entry.stats.str = 10
entry.stats.agi = 10
entry.stats.int = 10
entry.stats.max_life = 100
entry.stats.max_mana = 100
entry.stats.armour = 2
entry.stats.dps = 15
entry.stats.hp_regen = 1
entry.stats.mp_regen = 5
database.units.Write(entry)

--------------------------------------------------------------------

entry = database.units.GetTemplate()
entry.id = constants.heroes.pyromaniac
entry.hero_class = constants.hero_class.pyromaniac
entry.base_as_cd = 0.6
entry.base_ms = 330
entry.abil_list = {}
entry.stats.str = 10
entry.stats.agi = 10
entry.stats.int = 10
entry.stats.max_life = 100
entry.stats.max_mana = 100
entry.stats.armour = 2
entry.stats.dps = 15
entry.stats.hp_regen = 1
entry.stats.mp_regen = 5
database.units.Write(entry)

--------------------------------------------------------------------

entry = database.units.GetTemplate()
entry.id = constants.heroes.demolitionist
entry.hero_class = constants.hero_class.demolitionist
entry.base_as_cd = 1.2
entry.base_ms = 330
entry.abil_list = {}
entry.stats.str = 10
entry.stats.agi = 10
entry.stats.int = 10
entry.stats.max_life = 100
entry.stats.max_mana = 100
entry.stats.armour = 2
entry.stats.dps = 15
entry.stats.hp_regen = 1
entry.stats.mp_regen = 5
database.units.Write(entry)

--------------------------------------------------------------------
-- mobs
--------------------------------------------------------------------

entry = database.units.GetTemplate()
entry.id = constants.waves.w1
entry.base_as_cd = 1
entry.base_ms = 260
entry.stats.max_life = 8
entry.stats.dps = 3
entry.stats.armour = 1

database.units.Write(entry)