---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 28.11.2022 11:18
---

-- чекаем типизацию глобалок да да
-- изза фейковых типов оно не стандартный инт и
-- и поэтому playerslotstate != handle
-- пиздец чё

--

--playerslotstate != handle

local player = Player(14)

if(PLAYER_SLOT_STATE_PLAYING ~= GetPlayerSlotState(player))then
  PLAYER_SLOT_STATE_EMPTY = HandleToPlayerslotstate(PLAYER_SLOT_STATE_EMPTY)
  PLAYER_SLOT_STATE_PLAYING = HandleToPlayerslotstate(PLAYER_SLOT_STATE_PLAYING)
  PLAYER_SLOT_STATE_LEFT = HandleToPlayerslotstate(PLAYER_SLOT_STATE_LEFT)
end