---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 24.10.2022 11:22
---

--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------

database_modules = {}
local modules = database_modules
SDoFile( "containers\\database\\dbmodules\\units.lua")
SDoFile( "containers\\database\\dbmodules\\items.lua")
SDoFile( "containers\\database\\dbmodules\\abilities.lua")
database_modules = nil

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

database = {
  units = modules.units,
  items = modules.items,
  abilities = modules.abilities,
}