---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 07.06.2023 2:23
---

---@shape heroClassDef
---@field unitid string
---@field restriction string
---@field restriction_error string


local branch = NewBranch() --branch<heroClass>

---@param hero_class heroClass
---@param unitid string
---@param restriction string
---@param restriction_error string
local function NewHeroClassDef(hero_class, unitid, restriction, restriction_error)
  ---@type heroClassDef
  local def
  def = --[[---@type heroClassDef]]{}
  def.unitid = unitid
  def.restriction = restriction
  def.restriction_error = restriction_error

  branch:set(hero_class, def)
end

local function Init()
  NewHeroClassDef("none", "Hpal", "", "")
  NewHeroClassDef("stalker", "H000", "только для Сталкера", "С этим справится только Сталкер.")
  NewHeroClassDef("engineer", "H001", "только для Инженера", "Только Инженеру под силу разобраться с этим.")
  NewHeroClassDef("medic", "H002", "только для Медика", "Эту штуку опознает только Медик.")
  NewHeroClassDef("sniper", "H003", "только для Снайпера", "Лишь Снайпер найдёт этому применение.")
  NewHeroClassDef("gunner", "H004", "только для Пулемётчика", "Лишь у Пулемётчика это раскорется.")
  NewHeroClassDef("racketeer", "H005", "только для Ракетчика", "Эту хню поднимет только Ракетчик.")
  NewHeroClassDef("pyro", "H006", "только для Пироманьяка", "С этим зажжёт лишь Пироманьяк.")
  NewHeroClassDef("demolitionist", "H007", "только для Подрывника", "Только у Подрывника это хорошо рванёт.")
end

Init()

---@param hero_class heroClass
---@return string
local function GetUnitId(hero_class)
  ---@type heroClassDef
  local def = branch:get(hero_class)
  return def.unitid
end

---@param hero_class heroClass
---@return string
local function GetRestriction(hero_class)
  ---@type heroClassDef
  local def = branch:get(hero_class)
  return def.restriction
end

---@param hero_class heroClass
---@return string
local function GetRestrictionError(hero_class)
  ---@type heroClassDef
  local def = branch:get(hero_class)
  return def.restriction_error
end

heroClassDef = {
  GetUnitId = GetUnitId,
  GetRestriction = GetRestriction,
  GetRestrictionError = GetRestrictionError,
}