---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 07.06.2023 2:32
---

---@shape itemSlotDef
---@field description string
---@field restriction string

local branch = NewBranch() --branch<itemSlotDef>

---@param item_slot itemSlot
---@param description string
---@param restriction string
local function AddItemTypeDef(item_slot, description, restriction)
  ---@type itemSlotDef
  local def
  def = --[[---@type itemSlotDef]]{}
  def.description = description
  def.restriction = restriction

  branch:set(item_slot, def)
end

local function Init()
  AddItemTypeDef("undefined", "?", "%s")
  AddItemTypeDef("none", "", "%s")
  AddItemTypeDef("weapon", "Оружие", "Вы можете носить не больше %s Оружий!")
  AddItemTypeDef("armour", "Броня", "Вы можете носить не больше %s Брони!")
  AddItemTypeDef("set", "Сет", "Вы можете носить не больше %s Сета!")
  AddItemTypeDef("accessory", "Аксессуар", "Вы можете носить не больше %s Аксессуаров!")

end

Init()

---@param item_slot itemSlot
---@return string
function GetItemSlotDescription(item_slot)
  ---@type itemSlotDef
  local def = branch:get(item_slot)
  return def.description
end


---@param item_slot itemSlot
---@param limit number
---@return string
function BuildRestriction(item_slot, limit)
  ---@type itemSlotDef
  local def = branch:get(item_slot)
  return string.format(def.restriction, limit)
end


itemSlotDef = {
  GetDescription = GetItemSlotDescription,
  BuildRestriction = BuildRestriction,
}