---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 06.06.2023 21:51
---

---@shape itemTypeDef
---@field description string

local branch = NewBranch() --branch<itemTypeDef>

---@param item_type itemType
---@param description string
local function AddItemTypeDef(item_type, description)
  ---@type itemTypeDef
  local def
  def = --[[---@type itemTypeDef]]{}
  def.description = description

  branch:set(item_type, def)
end

local function Init()
  AddItemTypeDef("undefined", "Неопределённое")
  AddItemTypeDef("equipment", "Экипировка")
  AddItemTypeDef("resource", "Ресурс")
  AddItemTypeDef("material", "Материал")
  AddItemTypeDef("recipe", "Рецепт")
  AddItemTypeDef("consumable", "Расходуемое")
end

Init()

---@field item_type itemType
function GetItemTypeDescription(item_type)
  ---@type itemTypeDef
  local def = branch:get(item_type)
  return def.description
end


itemTypeDef = {
  GetDescription = GetItemTypeDescription
}