---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 07.06.2023 2:11
---


---@shape statDef
---@field key statKey
---@field description_index integer
---@field name string
---@field postfix string

local branch = NewBranch() --branch<statDef>

---@param key statKey
---@param description_index integer
---@param name string
---@param postfix string
local function NewStatDef(key, description_index, name, postfix)
  ---@type statDef
  local def
  def = --[[---@type statDef]]{}
  def.name = name
  def.description_index = description_index
  def.key = key
  def.postfix = postfix

  branch:set(key, def)
end


---@return statKey[]
local function GetAllStatKeys()
  ---@type statKey[]
  local defs = {}

  branch:foreach(function(k, v)
    ---@type statDef
    local def = v
    defs[def.description_index] = def.key

    return false
  end)

  return defs
end


local function Init()
  NewStatDef("str",           1, 	  "Сила",                   "")
  NewStatDef("agi",           2, 	  "Ловкость",               "")
  NewStatDef("int",           3, 	  "Интеллект",              "")
  NewStatDef("dmg",           4, 	  "Урон",                   "")
  NewStatDef("dps",           5, 	  "Урон в сек",             "")
  NewStatDef("armour",        6, 	  "Броня",                  "")
  NewStatDef("life_max",      7, 	  "Здоровье",               "")
  NewStatDef("mana_max",      8, 	  "Мана",                   "")
  NewStatDef("life_regen",    9, 	  "ХП в сек",               "")
  NewStatDef("mana_regen",    10, 	"МП в сек",               "")
  NewStatDef("as_percent",    11, 	"Скорость Атаки",         "%")
  NewStatDef("move_speed",    12, 	"Скорость Передвижения",  "")
  NewStatDef("sight_radius",  13, 	"Обзор",                  "")
  NewStatDef("attack_range",  14, 	"Дальность Атаки",        "")
end

Init()




---@param stat_key statKey
---@param value number
---@return string
local function BuildDescription(stat_key, value)
  ---@type statDef
  local stat = branch:get(stat_key)

  local sign = value < 0 and "-" or "+"

  return string.format("%s: %s%s%s", stat.name, sign, value, stat.postfix)
end

statDef = {
  BuildDescription = BuildDescription,
  GetAllStatKeys = GetAllStatKeys,
}