---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 27.11.2022 8:42
---

--[[
module messages
levels: info, debug, local_error, game_error,
SendLocal(pid, msg_level, msg, ...)
SendGlobal(msg_level, msg, ...)
]]--

--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------

---@class msg_level : integer

local levels = {
  info = 1,
  debug = 2,
  game_error = 3,
  nothing = 4,
}

local msg_prefix = {
  [levels.info] = "|cffffff00[info]|r: ",
  [levels.debug] = "|cff8000ff[debug]|r: ",
  [levels.game_error] = "|cffff0000[game error]|r: ",
  [levels.nothing] = ""
}

local msg_duration = {
  [levels.info] = 20,
  [levels.debug] = 40,
  [levels.game_error] = 60,
  [levels.nothing] = 20,
}

local isTracebackEnabled = false;

---@param level msg_level
---@return string
local function GetPrefix(level)
  return msg_prefix[level]
end

---@param level msg_level
---@return integer
local function GetDuration(level)
  return msg_duration[level]
end

---@param pid integer
---@param level msg_level
---@param msg string
local function SendLocal(pid, level, msg, ...)
  msg = GetPrefix(level) .. msg

  if(#{...} > 0)then msg = string.format(msg, ...) end

  if(GetLocalPlayer() ~= Player(pid))then return end

  DisplayTimedTextToPlayer( GetLocalPlayer(), 0, 0, GetDuration(level), msg)
  printc(msg)

  if(isTracebackEnabled == false)then return end
  msg = debug.traceback()
  DisplayTimedTextToPlayer( GetLocalPlayer(), 0, 0, GetDuration(level), msg)
  printc(msg)

end

---@param level msg_level
---@param msg string
local function Send(level, msg, ...)
  msg = GetPrefix(level) .. msg

  if(#{...} > 0)then msg = string.format(msg, ...) end

  DisplayTimedTextToPlayer( GetLocalPlayer(), 0, 0, GetDuration(level), msg)
  printc(msg)

  if(isTracebackEnabled == false)then return end
  msg = debug.traceback()
  DisplayTimedTextToPlayer( GetLocalPlayer(), 0, 0, GetDuration(level), msg)
  printc(msg)
end

--------------------------------------------------------------------

---@param flag boolean
local function IncludeTraceback(flag)
  Send(levels.info, "Messages will now include stack trace: %s", flag)
  isTracebackEnabled = flag
end

local function EnableTraceback()
  IncludeTraceback(true)
end

local function DisableTraceback()
  IncludeTraceback(false)
end

--------------------------------------------------------------------

---@param msg string
local function I_AM_TOO_LAZY_TO_WRITE_SHITTON_OF_ARGS_WHILE_DEBUGGING(msg, ...)
  Send(levels.debug, msg, ...)
end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

messages = {
  levels = levels,
  Send = Send,
  SendLocal = SendLocal,
  EnableTraceback = EnableTraceback,
  DisableTraceback = DisableTraceback,
  p = I_AM_TOO_LAZY_TO_WRITE_SHITTON_OF_ARGS_WHILE_DEBUGGING,
}

--messages.SendLocal(pid, messages.levels.info, "error while ending chat record")
--messages.Send(messages.levels.info, "ech")