---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 06.06.2023 4:04
---

Database = {}

local branch_items = NewBranch() --branch<itemData>
local branch_units = NewBranch() --branch<unitData>

---@param item_data itemData
function Database.AddItem(item_data)
  branch_items:set(fourci(item_data.id), item_data)
end

---@param itemid string
---@return itemData
function Database.ReadItem(itemid)
  local t = tableDeepCopy(branch_items:get(fourci(itemid)))
  return t --suppress error w/e
end

---@return branch
function Database.GetItemsBranchCopy()
  local copy = tableDeepCopy(branch_items)
  return copy
end

---@param unit_data unitData
function Database.AddUnit(unit_data)
  branch_units:set(fourci(unit_data.id), unit_data)
end

---@param unitid string | integer
---@return unitData
function Database.ReadUnit(unitid)
  unitid = fourci(unitid)

  local data = branch_units:get(unitid)

  if(data == nil)then
    Logger.SendError("Database.Unit -> unitid %s not found, returning base proto", unitid)
    return GetUnitDataProto()
  end

    ---@type unitData
  local copy = tableDeepCopy(data)
  return copy
end

