---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 06.06.2023 4:06
---

---@shape itemVisuals
---@field icon icon           --ITEM_SF_ICON
---@field model string        --ITEM_SF_MODEL_USED
---@field color_r number      --ITEM_IF_TINTING_COLOR_RED
---@field color_g number      --ITEM_IF_TINTING_COLOR_GREEN
---@field color_b number      --ITEM_IF_TINTING_COLOR_BLUE
---@field color_a number      --ITEM_IF_TINTING_COLOR_ALPHA
---@field model_scale number  --ITEM_RF_SCALING_VALUE

---@shape itemEvents
---@field onEquip fun(self: item, u: unit) | nil
---@field onDrop fun(self: item, u:unit) | nil
---@field onUse fun(self:item, u:unit) | nil

---@shape itemFlags
---@field item_type itemType
---@field item_slot itemSlot
---@field hero_unique heroClass
---@field is_single boolean

---@shape itemData
---@field id string
---@field name string
---@field sign string
---@field icon icon
---@field stats statList | nil
---@field flags itemFlags
---@field events itemEvents

---@type itemData
local prototype = {
  id = "null",
  name = "prototype item",
  sign = "prototype's sign",
  icon = "ReplaceableTextures\\WorldEditUI\\Editor-Force.blp",
  stats = stats.GetEmptyStatsTemplate(),
  flags = {
    item_type = "undefined",
    item_slot = "undefined",
    hero_unique = "none",
    is_single = false,
  },
  events = {
    onEquip = DoNothing,
    onDrop = DoNothing,
    onUse = DoNothing,
  }
}

---@param entry itemData
function NewItemDefinition(entry)
  if(entry.flags.item_type == "equipment" and entry.flags.item_slot == "none")then
    Logger.SendError("item %s has unacceptable flags: item_type: %s, item_slot :%s", entry.id, entry.flags.item_type, entry.flags.item_slot)
  end

  if(entry.flags.item_type ~= "equipment" and entry.stats ~= nil)then
    Logger.SendError("item %s has unacceptable config: item_type : %s, has stats!", entry.id, entry.flags.item_type)
  end

  Database.AddItem(tableMergeStrict(tableDeepCopy(prototype), entry))
end
