---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 06.06.2023 4:06
---

---@shape unitBaseStats
---@field attackspeed number

---@shape unitData
---@field id string
---@field name string
---@field stats statList
---@field base_stats unitBaseStats
---@field hero_class heroClass | nil
---@field base_events UnitBaseEventFuncList | nil

---@type unitData
local prototype = {
  id = "null",
  name = "prototype",
  stats = stats.GetEmptyStatsTemplate(),
  hero_class = "none",
  base_stats = {
    attackspeed = 5,
  },
  base_events = {
    onDoDamage = DoNothing,
    onGetDamage = DoNothing,
    onAttack = DoNothing,
    onCast = DoNothing,
    onKill = DoNothing,
    onDeath = DoNothing,
  },
}

---@param entry unitData
function NewUnitDefinition(entry)
  Database.AddUnit(tableMergeStrict(tableDeepCopy(prototype), entry))
end

---@return unitData
function GetUnitDataProto()
  ---@type unitData
  local copy = tableDeepCopy(prototype)
  return copy
end