---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 21.07.2022 13:39
---

local isBuild = false

if(isBuild)then
    EXTERNAL_PATH = "src\\"
else
    EXTERNAL_PATH = "Maps\\gs2.0\\src\\"
end

print(EXTERNAL_PATH)

function SDoFile(path)
    dofile(EXTERNAL_PATH .. path)
end

function s_loadfile(path)
    return loadfile(EXTERNAL_PATH .. path)
end


SDoFile("main.lua")