---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 10.11.2022 4:59
---

---@class gshopPreset
---@field id string
---@field soldItems table

---@type gshopPreset
local template_gshopPreset = {
  presetName = nil,
  soldItems = {}
}


--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------

local branch = storage.CreateNewBranch(storage.branch_ids.gshoppreset)
privateDataRequest.register.gshoppreset(branch)

local preset_id = {
  goblin_weapon_shop = 1,
  goblin_armour_shop = 2,
}

---@return gshopPreset
local function GetTemplate()
  return table.deepCopy(template_gshopPreset)
end

---@param preset_id integer
---@param soldItemsTable table
local function AddPreset(preset_id, soldItemsTable)
  local preset = GetTemplate()
  preset.id = preset_id
  preset.soldItems = soldItemsTable

  branch:set(preset_id, preset)
end

local function InitPresets()
  AddPreset(preset_id.goblin_weapon_shop, {
    constants.items.handmade_weapon_sniper,
    constants.items.handmade_weapon_stalker,
    constants.items.handmade_weapon_pyromaniac,
    constants.items.handmade_weapon_gunner,
    constants.items.handmade_weapon_racketeer,
    constants.items.handmade_weapon_medic,
    constants.items.handmade_weapon_engineer,
    constants.items.handmade_weapon_demolitionist,
    constants.items.orb_of_darkness,
  })

  AddPreset(preset_id.goblin_armour_shop, {
    constants.items.goblin_helmet,
    constants.items.goblin_armour,
    constants.items.goblin_boots,
    constants.items.goblin_gloves,
    constants.items.goblin_cape,
    constants.items.beauty_pendant,
    constants.items.goblin_armoured_suit,
  })

end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

-- todo: finish refactoring
-- move all constants here, like with storage

gshoppreset = {
  preset_id = preset_id,
  InitPresets = InitPresets,
}



