---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 26.11.2022 6:32
---

--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------

local recorders = {}


---@param pid integer
---@return boolean, string
local function EndRecord(pid)
  local chatRecord

  if(recorders[pid] == nil)then
    messages.SendLocal(pid, messages.levels.info, "Вы не стартовали чтение чата для загрузки кода!")
    return false, nil
  end

  chatRecord = recorders[pid]
  recorders[pid] = nil

  DestroyTrigger(chatRecord.trig)

  return true, chatRecord.text
end


---@param pid integer
---@return boolean
local function StartRecord(pid)
  local chatRecord

  if(recorders[pid] ~= nil)then
    local str = "Вы уже пытаетесь загрузить код, завершите старый командой '%s' чтобы попробовать снова"

    messages.SendLocal(pid, messages.levels.info, str, constants.chat_commands.manual_save_end)
    return false
  end

  chatRecord = {}
  recorders[pid] = chatRecord

  chatRecord.trig = CreateTrigger()
  chatRecord.text = ""

  local str = "Отправляйте свой код в следующих сообщениях в чат. Вы можете разделять его как хотите, но чтобы он заработал, вам нужно ввести его весь. Как закончите, напишите \'-savecode end\' для попытки загрузки"
  messages.SendLocal(pid, messages.levels.info, str)

  TriggerRegisterPlayerChatEvent(chatRecord.trig, Player(pid), "", false)
  TriggerAddAction(chatRecord.trig, function()
    local str = GetEventPlayerChatString()

    if(str ~= constants.chat_commands.manual_save_end and str ~= constants.chat_commands.manual_save_start)then
      chatRecord.text = chatRecord.text .. str
      local str2 = "часть кода получена, для попытки загрузки введите \'%s\'"
      messages.SendLocal(pid, messages.levels.info, str2, constants.chat_commands.manual_save_end)
    end

  end)

  return true
end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

saveloader_modules.chatRecorder = {
  StartRecord = StartRecord,
  EndRecord = EndRecord
}