---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 26.11.2022 6:52
---

---@param content table
---@return string
local function Encode(content)
  local str_as_json = json.encode(content)
  local str_as_json_as_base64 = base64.encode(str_as_json)

  return str_as_json_as_base64
end


---@param str_as_json_as_base64 string
---@return table
local function decode(str_as_json_as_base64)
  local str_as_json = base64.decode(str_as_json_as_base64)
  local content = json.decode(str_as_json)

  return content
end


---@param str_as_json_as_base64 string
---@return table
local function Validate(str_as_json_as_base64)
  return pcall(decode, str_as_json_as_base64)
end


---@param str_as_json_as_base64 string
---@return boolean, table
local function TryDecode(str_as_json_as_base64)
  local is_valid, content, error = Validate(str_as_json_as_base64)

  if(is_valid == false)then
    local template = "String you trying to decode is invalid|n error: %s"
    print(string.format(template, tostring(content)))
    return is_valid, nil
  end

  return is_valid, content
end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

saveloader_modules.contentEncoder = {
  Encode = Encode,
  Decode = TryDecode,
  Validate = Validate,
}