---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 26.11.2022 8:10
---

---@class saveData
---@field unitid string
---@field items table<string>

---@type saveData
local template = {
  unitid = nil,
  items = nil,
}

--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------


---@return saveData
local function GetTemplateCopy()
  return table.deepCopy(template)
end


---@param pid integer
---@param saveData saveData
local function Restore(pid, saveData)
  local unit, item

  unit = gplayer.CreatePlayerHero(pid, saveData.unitid)

  if(unit == nil)then
    messages.SendLocal(pid, messages.levels.info, "error while creating hero")
    return
  end

  for _, v in pairs(saveData.items)do
    item = gitem.Create(v, 0, 0)
    UnitAddItem(unit, item)
  end

end


---@param pid integer
---@return boolean, saveData
local function Create(pid)
  local saveData, hero, item

  saveData = GetTemplateCopy()

  hero = privateDataRequest.gplayer(pid).hero

  if(hero == nil)then
    messages.SendLocal(pid, messages.levels.info, "error: no hero to save")
    return false
  end

  saveData.unitid = GetUnitTypeId(hero)
  saveData.items = saveData.items or {}

  for i = 0, 5 do
    item = UnitItemInSlot(hero, i)
    if(item ~= nil)then
      table.insert(saveData.items, GetItemTypeId(item))
    end
  end

  return true, saveData
end


--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

saveloader_modules.savedataGenerator = {
  Create = Create,
  Restore = Restore,
}