---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 30.11.2022 22:57
---

--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------

--[[
function UnitAddAbilityEx(unit, abilityid)
  UnitAddAbility(unit, abilityid)
  events.ability.invoke(abilityid, EX_EVENT_ABILITY_ON_ADD, unit, abilityid)
end

function UnitRemoveAbilityEx(unit, abilityid)
  UnitRemoveAbility(unit, abilityid)
  events.ability.invoke(abilityid, EX_EVENT_ABILITY_ON_REMOVE, unit, abilityid)
end
]]--


---@param unit unit
---@param abilityid integer
local function AddAbility(unit, abilityid)
  UnitAddAbility(unit, fourcc(abilityid))
  events.invoke.ability.onAdd(unit, abilityid)
end


---@param unit unit
---@param abilityid integer
local function RemoveAbility(unit, abilityid)
  UnitAddAbility(unit, fourcc(abilityid))
  events.invoke.ability.onRemove(unit, abilityid)
end


---@param caster unit
---@param target unit
---@param abilityid integer
local function CastAbility(caster, target, abilityid)
  events.invoke.ability.onCast(abilityid, caster, target)
end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

gability = {
  Add = AddAbility,
  Remove = RemoveAbility,
  Cast = CastAbility,
}