---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 06.06.2023 21:32
---

constants = {}
constants.PLAYER_ENEMY = Player(10)
constants.ability_spellbook = "Aspb"          --"sbok" is item