---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 04.06.2023 5:08
---

---@class item : itemData
---@field unitInventory : unitInventory
-- functions are grabbed because of explicit type in constructor

---@param itemid string
---@param x number
---@param y number
function NewItem(itemid, x, y)
  ---@type item
  local item = CreateItem(fourcc(itemid), x, y)


  function item:init()
    local item_data = Database.ReadItem(itemid)

    tableAddValues(self, item_data)

    local id = fourcc(item_data.id)

    SetBaseItemStringFieldById(id, ITEM_SF_ICON, item_data.icon)
    SetBaseItemStringFieldById(id, ITEM_SF_NAME, item_data.name)
    SetBaseItemStringFieldById(id, ITEM_SF_TOOLTIP_NORMAL, item_data.name)

    --SetBaseItemStringFieldById(id, ITEM_SF_DESCRIPTION, desc)
    --SetBaseItemStringFieldById(id, ITEM_SF_TOOLTIP_EXTENDED, desc)
  end


  function item:printName()
    printd(GetItemName(--[[---@type item]]self))
  end

  item:init()

  return item
end
