---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 04.06.2023 3:41
---

---@class unit : unitData
---@field base_stats unitBaseStats
---@field inventory unitInventory
---@field events UnitEventList
-- functions are grabbed because of explicit type in constructor


---@param owner player
---@param unitid string
---@param x number
---@param y number
---@return unit
function NewUnit(owner, unitid, x, y)

  ---@type unit
  local u = CreateUnit(owner, fourcc(unitid), x, y, 0)

  ---@return string
  function u:getName()
    return GetUnitName(--[[---@type unit]]self)
  end

  function u:printName()
    printd(GetUnitName(--[[---@type unit]]self))
  end

  function u:init()
    --grab stats from db
    local unit_data = Database.ReadUnit(GetUnitTypeId(self))
    tableAddValues(self, unit_data)

    self.inventory = NewUnitInventory(self)
    self.events = NewUnitEventList( --[[---@type UnitBaseEventFuncList]] unit_data.base_events)

    SetUnitDamageDicesByIndex(--[[---@type unit]]self, 0, 1)
    SetUnitDamageDicesSideByIndex(--[[---@type unit]]self, 0, 1)

    UnitStatUpdater.ForceUpdate(self)
  end

  ---@param item item
  function u:EquipItem(item)
    self.inventory:equipItem(item)
  end

  ---@param item item
  function u:DropItem(item)
    self.inventory:dropItem(item)
  end


  u:init()

  return u
end