---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 24.10.2022 0:49
---

---@class stats
---@field str number
---@field agi number
---@field int number
---@field damage number
---@field armour number
---@field max_life number
---@field max_mana number
---@field hp_regen number
---@field mp_regen number
---@field dps number
---@field attackspeed number

local empty_stats_template = {
  str = 0,
  agi = 0,
  int = 0,
  damage = 0,
  armour = 0,
  max_life = 0,
  max_mana = 0,
  hp_regen = 0,
  mp_regen = 0,
  dps = 0,
  attackspeed = 0,
}

--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------

---@return stats
local function GetEmptyTemplate()
  return table.deepCopy(empty_stats_template)
end

---@param main stats
---@param delta stats
local function Sum(main, delta)
  for k, _ in pairs(main)do
    main[k] = main[k] + delta[k]
  end
end

---@param main stats
---@param delta stats
local function Sub(main, delta)
  for k, _ in pairs(main)do
    main[k] = main[k] - delta[k]
  end
end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

stats = {
  GetEmptyTemplate = GetEmptyTemplate,
  sum = Sum,
  sub = Sub,
}