---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 24.10.2022 11:20
---

constants = {}

constants.map_version = "non-existing alpha"

constants.min_attack_speed = 20
constants.max_attack_speed = 500

constants.heroes = {}
constants.heroes.stalker = "H000"
constants.heroes.medic = "H001"
constants.heroes.engineer = "H002"
constants.heroes.sniper = "H003"
constants.heroes.gunner = "H004"
constants.heroes.racketeer = "H005"
constants.heroes.pyromaniac = "H006"
constants.heroes.demolitionist = "H007"


constants.items = {}
constants.items.orb_of_darkness = "I000"


constants.items.handmade_weapon_stalker = "I001"
constants.items.handmade_weapon_medic = "I002"
constants.items.handmade_weapon_engineer = "I003"
constants.items.handmade_weapon_sniper = "I004"
constants.items.handmade_weapon_gunner = "I005"
constants.items.handmade_weapon_racketeer = "I006"
constants.items.handmade_weapon_pyromaniac= "I007"
constants.items.handmade_weapon_demolitionist = "I008"


constants.items.goblin_helmet = "I009"
constants.items.goblin_armour = "I00A"
constants.items.goblin_boots = "I00B"
constants.items.goblin_gloves = "I00C"
constants.items.goblin_cape = "I00D"
constants.items.beauty_pendant = "I00E"
constants.items.goblin_armoured_suit = "I00F"


-- max created itemid currently is I00Z

constants.waves = {}
constants.waves.w1 = "n000"


constants.item_types = {}
constants.item_types.permanent = 1      -- | постоянный предмет
constants.item_types.resource = 2       -- | руда/камни, стакается
constants.item_types.material = 3       -- | материал, не стакается
constants.item_types.recipe = 4         -- | рецепты
constants.item_types.consumable = 5     -- | расходники - зелья, еда, етк


constants.item_slots = {}
constants.item_slots.none = 0           -- | нет типа
constants.item_slots.weapon = 1
constants.item_slots.armour = 2
constants.item_slots.full_set = 3
constants.item_slots.accessory = 4


constants.hero_class = {}
constants.hero_class.none = 0           -- | нет привязки
constants.hero_class.stalker = 1
constants.hero_class.medic = 2
constants.hero_class.engineer = 3
constants.hero_class.sniper = 4
constants.hero_class.gunner = 5
constants.hero_class.racketeer = 6
constants.hero_class.pyromaniac = 7
constants.hero_class.demolitionist = 8


constants.max_permanent_item_count = {}
constants.max_permanent_item_count[constants.item_slots.weapon] = 2     -- | 2 оружия
constants.max_permanent_item_count[constants.item_slots.armour] = 1     -- | 1 броня
constants.max_permanent_item_count[constants.item_slots.full_set] = 1   -- | 1 сет
constants.max_permanent_item_count[constants.item_slots.accessory] = 4  -- | 4 акса


constants.chat_commands = {}
constants.chat_commands.manual_save_start = "-savecode begin"
constants.chat_commands.manual_save_end = "-savecode end"


constants.abilities = {}
constants.abilities.stalker = {}
constants.abilities.stalker.q = "A002"
