---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 11.06.2023 1:19
---

---@param caster unit
local function OnNormalStoneMine(caster)

end

---@param caster unit
---@param target unit
---@param damage number
local function OnNormalStoneDamaged(caster, target, damage)
  SetEventDamage(1)
  printdf("rolled: %s", GetRandomInt(0, 100))
  OnNormalStoneMine(caster)
end

RockMiningCorp = {
  OnNormalStoneDamaged = OnNormalStoneDamaged
}

--[[
GemWhite.mdl

war3mapImported\IronOre.mdl
war3mapImported\SilverOre.mdl

war3mapImported\OreCrystal.mdl
]]