---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 07.06.2023 9:16
---

---@alias UnitOnCastDelegate fun(caster: unit, target: unit, abilityid: string)

---@class EventUnitOnCast : EventUnitBase<UnitOnCastDelegate>
---@field add fun(self: EventUnitOnCast, action: UnitOnCastDelegate)
---@field remove fun(self: EventUnitOnCast, action: UnitOnCastDelegate)

---@return EventUnitOnCast
function NewEventUnitOnCast()
  ---@type EventUnitOnCast
  local eve = --[[---@type EventUnitOnCast]] NewEventUnitBase()

  ---@param caster unit
  ---@param target unit
  ---@param abilityid string
  function eve:invoke(caster, target, abilityid)
    self.is_used = true
    for i, v in ipairs(self.data)do
      v(caster, target, abilityid)
    end
    self.is_used = false
  end

  return eve
end