---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 07.06.2023 9:16
---

---@alias UnitOnDoDamageDelegate fun(source: unit, target: unit, damage: number)

---@class EventUnitOnDoDamage : EventUnitBase<UnitOnDoDamageDelegate>
---@field add fun(self: EventUnitOnDoDamage, action: UnitOnDoDamageDelegate)
---@field remove fun(self: EventUnitOnDoDamage, action: UnitOnDoDamageDelegate)

---@return EventUnitOnDoDamage
function NewEventUnitOnDoDamage()
  ---@type EventUnitOnDoDamage
  local eve = --[[---@type EventUnitOnDoDamage]] NewEventUnitBase()

  ---@param source unit
  ---@param target unit
  function eve:invoke(source, target)
    self.is_used = true
    for i, v in ipairs(self.data)do
      v(source, target, GetEventDamage())
    end
    self.is_used = false
  end

  return eve
end