---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 07.06.2023 9:16
---

---@alias UnitOnAttackDelegate fun(caster: unit, target: unit, damage: number)

---@class EventUnitOnAttack : EventUnitBase<UnitOnAttackDelegate>
---@field add fun(self: EventUnitOnAttack, action: UnitOnAttackDelegate)
---@field remove fun(self: EventUnitOnAttack, action: UnitOnAttackDelegate)

---@return EventUnitOnAttack
function NewEventUnitOnAttack()
  ---@type EventUnitOnAttack
  local eve = --[[---@type EventUnitOnAttack]] NewEventUnitBase()

  ---@param caster unit
  ---@param target unit
  function eve:invoke(caster, target)
    self.is_used = true
    for i, v in ipairs(self.data)do
      v(caster, target, GetEventDamage())
    end
    self.is_used = false
  end

  return eve
end