---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 07.06.2023 9:16
---

---@alias UnitOnDeathDelegate fun(target: unit, killer: unit)

---@class EventUnitOnDeath : EventUnitBase<UnitOnDeathDelegate>
---@field add fun(self: EventUnitOnDeath, action: UnitOnDeathDelegate)
---@field remove fun(self: EventUnitOnDeath, action: UnitOnDeathDelegate)

---@return EventUnitOnDeath
function NewEventUnitOnDeath()
  ---@type EventUnitOnDeath
  local eve = --[[---@type EventUnitOnDeath]] NewEventUnitBase()

  ---@param target unit
  ---@param killer unit
  function eve:invoke(target, killer)
    self.is_used = true
    for i, v in ipairs(self.data)do
      v(target, killer)
    end
    self.is_used = false
  end

  return eve
end