---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 07.06.2023 9:16
---

---@alias UnitOnKillDelegate fun(target: unit, killer: unit)

---@class EventUnitOnKill : EventUnitBase<UnitOnKillDelegate>
---@field add fun(self: EventUnitOnKill, action: UnitOnKillDelegate)
---@field remove fun(self: EventUnitOnKill, action: UnitOnKillDelegate)

---@return EventUnitOnKill
function NewEventUnitOnKill()
  ---@type EventUnitOnKill
  local eve = --[[---@type EventUnitOnKill]] NewEventUnitBase()

  ---@param target unit
  ---@param killer unit
  function eve:invoke(target, killer)
    self.is_used = true
    for i, v in ipairs(self.data)do
      v(target, killer)
    end
    self.is_used = false
  end

  return eve
end