---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 07.06.2023 9:20
---

---@shape UnitBaseEventFuncList
---@field onDoDamage UnitOnDoDamageDelegate | nil
---@field onGetDamage UnitOnGetDamageDelegate | nil
---@field onAttack UnitOnAttackDelegate | nil
---@field onCast UnitOnCastDelegate | nil
---@field onKill UnitOnKillDelegate | nil
---@field onDeath UnitOnDeathDelegate | nil


---@class UnitEventList
---@field onDoDamage EventUnitOnDoDamage
---@field onGetDamage EventUnitOnGetDamage
---@field onAttack EventUnitOnAttack
---@field onCast EventUnitOnCast
---@field onKill EventUnitOnKill
---@field onDeath EventUnitOnDeath


---@param event_func_list UnitBaseEventFuncList
---@return UnitEventList
function NewUnitEventList(event_func_list)
  ---@type UnitEventList
  local t= --[[---@type UnitEventList]]{}
  t.onDoDamage = NewEventUnitOnDoDamage()
  t.onGetDamage = NewEventUnitOnGetDamage()
  t.onAttack = NewEventUnitOnAttack()
  t.onCast = NewEventUnitOnCast()
  t.onKill = NewEventUnitOnKill()
  t.onDeath = NewEventUnitOnDeath()

  --merge with base event list from unit
  if(event_func_list ~= nil)then
    for k, v in pairs(event_func_list)do
      t[k]:add(v)
    end
  end

  return t
end