---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 27.11.2022 11:19
---

---missing definitions which parser cannot place

---@alias nothing: void

---@class handle
---@class code