---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 22.10.2022 14:07
---

-- prints directly into console
function printc(string) end

-- false: выводит только название карты
-- true: выводит путь от корня варика
---@param fromWar3Root boolean
---@return string
function GetMapFileName(fromWar3Root)  end