---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 06.06.2023 4:27
---

NewItemDefinition({
  id = "I000",
  name = "Orb of Darkness",
  sign = "Orbge ofge Darknessge",
  icon = "ReplaceableTextures\\CommandButtons\\BTNOrbOfDarkness.blp",
  stats = {
    str = 10,
    agi = 10,
    int = 10,
    dmg = 10,
    dps = 10,
    armour = 10,
    life_max = 10,
    mana_max = 10,
    life_regen = 10,
    mana_regen = 10,
    as_percent = 10,
    move_speed = 10,
    sight_radius = 10,
    attack_range = 10,
  },
  events = {},
  flags = {
    is_single = true,
    item_slot = "weapon",
    hero_unique = "stalker",
    item_type = "equipment",
  }
})

NewItemDefinition({
  id = "I001",
  name = "Stalk wep",
  sign = "asdf",
  icon = "ReplaceableTextures\\CommandButtons\\BTNOrbOfDarkness.blp",
  stats = {
    dps = 10,
  },
  events = {},
  flags = {
    is_single = false,
    item_slot = "weapon",
    hero_unique = "stalker",
    item_type = "equipment",
  }
})

NewItemDefinition({
  id = "I002",
  name = "Materialge",
  sign = "asdfasdfasdfasddf",
  icon = "ReplaceableTextures\\CommandButtons\\BTNHeartOfAszune.blp",
  flags = {
    is_single = false,
    item_slot = "none",
    hero_unique = "none",
    item_type = "material",
  },
  events = {
    onEquip = function(self, u)
      printdf("%s was equipped", GetItemName(self))
    end
  }
})

NewItemDefinition({
  id = "I003",
  name = "Ведро с болтами",
  sign = "Если хорошенько его потрясти, можно призвать мехагоблина",
  icon = "ReplaceableTextures\\CommandButtons\\BTNMagicVault",
  flags = {
    is_single = true,
    item_slot = "accessory",
    hero_unique = "none",
    item_type = "equipment",
  },
  events = {
    onEquip = function(item, u)
      SetItemBooleanField(item, ITEM_BF_ACTIVELY_USED, true)
      SetItemStringField(item, ITEM_SF_ABILITY_LIST, "Aspb")

      local a = GetItemAbility(item, fourcc("Aspb"))
      SetAbilityStringLevelField(a, ABILITY_SLF_SPELL_LIST, 0, "AI00")
      SetAbilityBooleanLevelField(a, ABILITY_BLF_SHARED_SPELL_COOLDOWN, 0, false)

    end
  }
})

