---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 06.06.2023 4:27
---

--region player heroes
NewUnitDefinition({
  id = "H000",
  name = "Сталкер",
  hero_class = "stalker",
  stats = {
    str = 10,
    agi = 10,
    int = 10,
    armour = 2,
    dps = 15,
    life_max = 100,
    life_regen = 1,
    mana_max = 100,
    mana_regen = 5,
    move_speed = 330,
    sight_radius = 800,
    attack_range = 750,
  },
  base_stats = {
    attackspeed = 1.2,
  }
})

NewUnitDefinition({
  id = "H001",
  name = "Инженер",
  hero_class = "engineer",
  stats = {
    str = 10,
    agi = 10,
    int = 10,
    armour = 2,
    dps = 15,
    life_max = 100,
    life_regen = 1,
    mana_max = 100,
    mana_regen = 5,
    move_speed = 330,
    sight_radius = 800,
    attack_range = 750,
  },
  base_stats = {
    attackspeed = 1.0,
  }
})

NewUnitDefinition({
  id = "H002",
  name = "Медик",
  hero_class = "medic",
  stats = {
    str = 10,
    agi = 10,
    int = 10,
    armour = 2,
    dps = 15,
    life_max = 100,
    life_regen = 1,
    mana_max = 100,
    mana_regen = 5,
    move_speed = 330,
    sight_radius = 800,
    attack_range = 750,
  },
  base_stats = {
    attackspeed = 1.4,
  }
})

NewUnitDefinition({
  id = "H003",
  name = "Снайпер",
  hero_class = "sniper",
  stats = {
    str = 10,
    agi = 10,
    int = 10,
    armour = 2,
    dps = 15,
    life_max = 100,
    life_regen = 1,
    mana_max = 100,
    mana_regen = 5,
    move_speed = 330,
    sight_radius = 800,
    attack_range = 750,
  },
  base_stats = {
    attackspeed = 1.6,
  }
})

NewUnitDefinition({
  id = "H004",
  name = "Пулемётчик",
  hero_class = "gunner",
  stats = {
    str = 10,
    agi = 10,
    int = 10,
    armour = 2,
    dps = 15,
    life_max = 100,
    life_regen = 1,
    mana_max = 100,
    mana_regen = 5,
    move_speed = 330,
    sight_radius = 800,
    attack_range = 750,
  },
  base_stats = {
    attackspeed = 0.8,
  }
})

NewUnitDefinition({
  id = "H005",
  name = "Ракетчик",
  hero_class = "racketeer",
  stats = {
    str = 10,
    agi = 10,
    int = 10,
    armour = 2,
    dps = 15,
    life_max = 100,
    life_regen = 1,
    mana_max = 100,
    mana_regen = 5,
    move_speed = 330,
    sight_radius = 800,
    attack_range = 750,
  },
  base_stats = {
    attackspeed = 1.3,
  }
})

NewUnitDefinition({
  id = "H006",
  name = "Пироманьяк",
  hero_class = "pyro",
  stats = {
    str = 10,
    agi = 10,
    int = 10,
    armour = 2,
    dps = 15,
    life_max = 100,
    life_regen = 1,
    mana_max = 100,
    mana_regen = 5,
    move_speed = 330,
    sight_radius = 800,
    attack_range = 750,
  },
  base_stats = {
    attackspeed = 0.6,
  }
})

NewUnitDefinition({
  id = "H007",
  name = "Подрывник",
  hero_class = "demolitionist",
  stats = {
    str = 10,
    agi = 10,
    int = 10,
    armour = 2,
    dps = 15,
    life_max = 100,
    life_regen = 1,
    mana_max = 100,
    mana_regen = 5,
    move_speed = 330,
    sight_radius = 800,
    attack_range = 750,
  },
  base_stats = {
    attackspeed = 1.2,
  }
})
--endregion player heroes

--region stones
NewUnitDefinition({
  id = "h000",
  name = "Глыба",
  stats = {
    armour = 0,
    dmg = 0,
    dps = 0,
    life_max = 15,
    life_regen = 0,
    mana_max = 0,
    mana_regen = 0,
    move_speed = 0,
    sight_radius = 0,
    attack_range = 0,
  },
  base_stats = {
    attackspeed = 1,
  },
  base_events = { onGetDamage = RockMiningCorp.OnNormalStoneDamaged },

})

--[[
events = {
  onGetDamage = function()
  ->
}


]]

--Doodads\LordaeronSummer\Terrain\LoardaeronRockChunks\LoardaeronRockChunks4.mdl

--endregion stones

--region waves
NewUnitDefinition({
  id = "n000",
  name = "Маленький Паучок",
  stats = {
    str = 10,
    agi = 10,
    int = 10,
    armour = 3,
    dmg = 3,
    dps = 0,
    life_max = 10,
    life_regen = 1,
    mana_max = 0,
    mana_regen = 0,
    move_speed = 260,
    sight_radius = 600,
    attack_range = 64,
  },
  base_stats = {
    attackspeed = 1,
  }
})
--endregion waves