---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 26.11.2022 10:23
---

---@class branch

--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------

local active_branches = {}

local function CreateNewBranch(branch_id)
  local branch = {
    data = {},

    get = function(self, k)
      if (self.data[k] == nil) then
        messages.Send(messages.levels.game_error, "data on key is nil: %s", k)
      end

      return self.data[k]
    end,

    set = function(self, k, v)
      if (self.data[k] ~= nil) then
        messages.Send(messages.levels.game_error, "data on key already exists: %s", k)
      end

      self.data[k] = v
    end,

    exists = function(self, k)
      return self.data[k] ~= nil
    end,

    free = function(self, k)
      local val = self.data[k]

      if (val == nil) then
        messages.Send(messages.levels.game_error, "data on key not exists to free: [key] %s", k)
        printd(debug.traceback())
      end

      self.data[k] = nil
      return val
    end
  }

  active_branches[branch_id] = branch

  return branch
end

---@param branch_id integer
---@return branch
local function GetBranchCopy(branch_id)
  return table.shadowCopy(active_branches[branch_id].data)
end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

storage = {
  CreateNewBranch = CreateNewBranch,
  GetBranchCopy = GetBranchCopy,
  branch_ids = {
    db_items = 0,
    db_units = 1,
    db_abilities = 2,
    chat_commands = 3,
    gitem = 4,
    gunit = 5,
    gplayer = 6,
    gshoppreset = 7,
    gshop = 8,
    sync = 9,
  }
}