---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 24.10.2022 18:49
---

--------------------------------------------------------------------
-- model
--------------------------------------------------------------------

---@class ability_dbEntry
---@field id string                   --| aka key
---@field events abilityevents        --|

---@type ability_dbEntry
local dbEntry_template_ability = {
  id = "id",
  events = events.GetAbilityEventsTemplate(),
}


--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------

local branch = storage.CreateNewBranch(storage.branch_ids.db_abilities)


---@return ability_dbEntry
local function GetTemplate()
  return table.deepCopy(dbEntry_template_ability)
end


---@param entry ability_dbEntry
local function Write(entry)
  local template = GetTemplate()
  entry = table.merge(template, entry)

  branch:set(fourci(entry.id), entry)
end


---@param objectid string
---@return ability_dbEntry
local function Read(objectid)
  return branch:get(fourci(objectid))
end


---@return ability_dbEntry[]
local function GetFullCopy()
  return storage.GetBranchCopy(storage.branch_ids.db_abilities)
end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

database_modules.abilities = {
  GetTemplate = GetTemplate,
  Write = Write,
  Read = Read,
  GetFullCopy = GetFullCopy,
}