---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 24.10.2022 19:33
---

---@class item_dbEntry
---@field id string               --| aka key
---@field name string             --| base name
---@field sign string             --| unique sign for item
---@field icon string             --| icon path
---@field type integer            --| item type
---@field slot integer            --| item_slot
---@field hero_class integer      --| hero class
---@field is_single boolean       --| can be used more than once
---@field stats stats             --| base stats
---@field events itemevents       --| events


---@type item_dbEntry
local dbEntry_template_item = {
  id = "null",
  name = "default_name",
  sign = "default_sign",
  icon = "ReplaceableTextures\\WorldEditUI\\Editor-Force.blp",
  type = constants.item_types.resource,
  slot = constants.item_slots.none,
  hero_class = constants.hero_class.none,
  is_single = false,
  stats = stats.GetEmptyTemplate(),
  events = events.GetItemEventsTemplate(),
}

--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------

local branch = storage.CreateNewBranch(storage.branch_ids.db_items)


---@return item_dbEntry
local function GetTemplate()
  return table.deepCopy(dbEntry_template_item)
end


---@param entry item_dbEntry
local function Write(entry)
  local template = GetTemplate()
  entry = table.merge(template, entry)

  branch:set(fourci(entry.id), entry)
end


---@param objectid string
---@return item_dbEntry
local function Read(objectid)
  return branch:get(fourci(objectid))
end


---@return item_dbEntry[]
local function GetFullCopy()
  return storage.GetBranchCopy(storage.branch_ids.db_items)
end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

database_modules.items = {
  GetTemplate = GetTemplate,
  Write = Write,
  Read = Read,
  GetFullCopy = GetFullCopy,
}