---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 24.10.2022 18:49
---

--------------------------------------------------------------------
-- model
--------------------------------------------------------------------

---@class dbunitmodule:dbmodule
---@field Write fun(entry: unit_dbEntry)
---@field Read fun(objectid: string): unit_dbEntry
---@field GetFullBranchCopy fun(key: string): unit_dbEntry[]
---@field GetEntryTemplate fun(): unit_dbEntry


---@class unit_dbEntry
---@field id string                   --| aka key
---@field hero_class integer          --| aka key
---@field base_as_cd number           --| cd of autoattack
---@field base_ms number              --| base movespeed
---@field stats stats                 --| base stats
---@field abil_list table<string>     --| abil list


---@type unit_dbEntry
local dbEntry_template_unit = {
  id = "null",
  hero_class = constants.hero_class.none,
  base_as_cd = 1,
  base_ms = 350,
  stats = stats.GetEmptyTemplate(),
  abil_list = {},
}


--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------

local branch = storage.CreateNewBranch(storage.branch_ids.db_units)


---@return unit_dbEntry
local function GetTemplate()
  return table.deepCopy(dbEntry_template_unit)
end


---@param entry unit_dbEntry
local function Write(entry)
  local template = GetTemplate()
  entry = table.merge(template, entry)

  branch:set(fourci(entry.id), entry)
end


---@param objectid string
---@return unit_dbEntry
local function Read(objectid)
  return branch:get(fourci(objectid))
end


---@return unit_dbEntry[]
local function GetFullCopy()
  return storage.GetBranchCopy(storage.branch_ids.db_units)
end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

database_modules.units = {
  GetTemplate = GetTemplate,
  Write = Write,
  Read = Read,
  GetFullCopy = GetFullCopy,
}