---
--- Generated by Luanalysis
--- Created by Siren.
--- DateTime: 06.06.2023 1:13
---

---@alias statKey "str"|"agi"|"int"|"dmg"|"dps"|"armour"|"life_max"|"mana_max"|"life_regen"|"mana_regen"|"as_percent"|"move_speed"|"sight_radius"|"attack_range"



