---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 29.05.2023 19:43
---

---@alias icon string

--[[

---low lvl
SDoFile("libs\\basic.lua")


-- standalone modules
SDoFile("libs\\modules\\Logger.lua")
SDoFile("libs\\modules\\Branch.lua")
--
SDoFile("libs\\modules\\Benchmark.lua")
SDoFile("libs\\modules\\ChatCommandList.lua")

SDoFile("libs\\enums\\defs\\statDef.lua")
SDoFile("libs\\enums\\defs\\itemTypeDef.lua")
SDoFile("libs\\enums\\defs\\itemSlotDef.lua")
SDoFile("libs\\enums\\defs\\heroClassDef.lua")

SDoFile("libs\\stats.lua")

SDoFile("libs\\constants.lua")

-- mid level
SDoFile("libs\\UnitStatUpdater.lua")
SDoFile("libs\\unitInventory.lua")

SDoFile("content\\RockMiningCorp.lua")

-- database things
SDoFile("libs\\database\\Database.lua")
SDoFile("libs\\database\\ItemData.lua")
SDoFile("libs\\database\\UnitData.lua")

SDoFile("libs\\database\\content\\ItemDefinitions.lua")
SDoFile("libs\\database\\content\\UnitDefinitions.lua")

-- event things
SDoFile("libs\\events\\EventUnitBase.lua")
SDoFile("libs\\events\\EventUnitOnDoDamage.lua")
SDoFile("libs\\events\\EventUnitOnGetDamage.lua")
SDoFile("libs\\events\\EventUnitOnAttack.lua")
SDoFile("libs\\events\\EventUnitOnCast.lua")
SDoFile("libs\\events\\EventUnitOnKill.lua")
SDoFile("libs\\events\\EventUnitOnDeath.lua")

SDoFile("libs\\events\\UnitEventList.lua")

SDoFile("libs\\Waves.lua")
-- high level
SDoFile("libs\\ItemIngameUpdater.lua")

SDoFile("libs\\unit.lua")
SDoFile("libs\\item.lua")
SDoFile("libs\\player.lua")

SDoFile("content\\ChatCommands.lua")
]]

--InitDebugHooks()

TimerStart(CreateTimer(), 1, false,function ()
  local t = {}

  for i = 0, 100 do
    local u = CreateUnit(Player(0), FourCC("Hvsh"), 0, 0, 0)

    function u:objectFunc(num)
      self.t = self.t or {}
      self.t[num] = num
    end

    t[i] = u
  end

  for i = 0, 100 do
    for j = 0, 10000 do
      local u = t[i]
      local status, error_msg = pcall(function()
        u:objectFunc(j)
      end)

      if(status == false)then
        printdf("i: %s, j: %s, err: %s", i, j, error_msg)
        return
      end

    end
  end

end)

--[[

TimerStart(CreateTimer(), 1, false,function ()
  InitPlayers()

  UpdateItemGameData()

  local u = NewUnit(Player(0), "H000", 0, 0)

  local rock = NewUnit(Player(15), "h000", -300, -300)

  local item = NewItem("I000", 0, 0)
  item = NewItem("I000", 0, 0)
  item = NewItem("I002", 0, 0)
  item = NewItem("I002", 0, 0)

  item = NewItem("I001", 0, 0)

  i = NewItem("I003", 100, 0)

  ---@field color_r number  --ITEM_IF_TINTING_COLOR_RED
  ---@field color_g number  --ITEM_IF_TINTING_COLOR_GREEN
  ---@field color_b number  --ITEM_IF_TINTING_COLOR_BLUE
  ---@field color_a number  --ITEM_IF_TINTING_COLOR_ALPHA -- works but very weird
  ---@field model_scale number --ITEM_RF_SCALING_VALUE    -- not works with items

  SetBaseItemStringFieldById(GetItemTypeId(item), ITEM_SF_MODEL_USED, "Ores\\OreCrystal.mdx")
  --SetItemStringField(item, ITEM_SF_MODEL_USED, "Ores\\OreCrystal.mdx")


end)
]]

--[[
Ведро с винтами

--todo:
0) drone for mining ROCKS and STONES
1) buildings
2) stackable items

]]

--[[

fake item description -> GetFrameByName(itemslot).DisableTooltip; Create own one and print info there


aggro system ?

abil events: onAdd, onRemove, onCast
unit: item drop; shared gold bounty;
shop: unitid; item_list: {itemid, charge_cd, stacks, cost}
craft: mats

item ->
CTooltip -> if enhanced tooltips disabled
CUberTooltip -> if enabled

item > boss -> drop is bound to unit

more inheritance?:
unit:
->hero
->waveMob
->boss


debug mod
-> event: chat command; action -> many debug chat commands are added; to not flood chat commands
]]