---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Siren.
--- DateTime: 24.10.2022 18:00
---

--------------------------------------------------------------------
-- private logic
--------------------------------------------------------------------

local branches = {}

---@type fun(item: item):gitemData
branches.gitemData = nil

---@type fun(shopid: string):gshopPreset
branches.gshopPreset = nil

---@type fun(item: item):gunitData
branches.gunitData = nil

---@type fun(pid: integer):gplayerData
branches.gplayerData = nil


---@param branch branch
local function Register_gitemData(branch)
  branches.gitemData = branch
end


---@param branch branch
local function Register_gshopPreset(branch)
  branches.gshopPreset = branch
end


---@param branch
local function Register_gunitData(branch)
  branches.gunitData = branch
end

---@param branch
local function Register_gplayerData(branch)
  branches.gplayerData = branch
end


---@param item item
---@return gitemData
local function Request_gitemData(item)
  if(branches.gitemData ~= nil)then
    return branches.gitemData:get(item)
  end
end


---@param shopid string
---@return gshopPreset
local function Request_gshopPreset(shopid)
  if(branches.gshopPreset ~= nil)then
    return branches.gshopPreset:get(shopid)
  end
end


---@param unit unit
---@return gunitData
local function Request_gunitData(unit)
  if(branches.gunitData ~= nil)then
    return branches.gunitData:get(unit)
  end
end


---@param pid integer
---@return gplayerData
local function Request_gplayerData(pid)
  if(branches.gplayerData ~= nil)then
    return branches.gplayerData:get(pid)
  end
end

--------------------------------------------------------------------
-- public functions
--------------------------------------------------------------------

privateDataRequest = {
  register = {
    gitem = Register_gitemData,
    gunit = Register_gunitData,
    gshoppreset = Register_gshopPreset,
    gplayer = Register_gplayerData,
  },
  gitemData = Request_gitemData,
  gunitData = Request_gunitData,
  gshopPreset = Request_gshopPreset,
  gplayer = Request_gplayerData,
}